// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GridBumpSeqRowColumn
{
    internal sealed partial class Vsix
    {
        public const string Id = "GridBumpSeqRowColumn.077f3b46-9a78-4912-b479-662d42489f40";
        public const string Name = "GridBumpSeqRowColumn";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
